[package]
name = "library_management"
version = "0.1.0"
edition = "2021"
[target.'cfg(windows)'.dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
